[package]
name = "petgraph-graphml"
version = "1.0.3"
authors = ["jonasbb"]

description = "GraphML output support for petgraph"
documentation = "https://docs.rs/petgraph-graphml/"
repository = "https://github.com/jonasbb/petgraph-graphml"
readme = "README.md"
keywords = ["graphml", "petgraph"]
license = "MIT/Apache-2.0"

[badges]
travis-ci = { repository = "jonasbb/petgraph-graphml", branch = "master", service = "github" }
maintenance = { status = "passively-maintained" }

[dependencies]
petgraph = "0.4.0"
version-sync = "0.8.0"
xml-rs = "0.8.0"
